# Form implementation generated from reading ui file 'rsaframe.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

#main function
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QApplication, QLineEdit, QPushButton, QLabel, QFileDialog
import sys
import random
import math
from Demo_chucnang import encrypt, decrypt,gcd,isprime,mod_inverse,generateKeys,pubKey,priKey
from Demo_chucnang import pubKey, priKey
from PyQt6.QtCore import QDir
#pyqt
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 600)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 10, 300, 31))
        self.label.setMinimumSize(QtCore.QSize(5, 6))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(380, 60, 20, 321))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine) 
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 300, 14))
        self.label_public_key = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_public_key.setGeometry(QtCore.QRect(60, 330, 321, 31))
        self.label_public_key.setObjectName("label_public_key")
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_2.setFont(font)  
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 43, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 280, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.nhap_BR = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nhap_BR.setGeometry(QtCore.QRect(60, 80, 321, 121))
        self.nhap_BR.setText("")
        self.nhap_BR.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.nhap_BR.setObjectName("nhap_BR")
        self.btn_maHoa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_maHoa.setGeometry(QtCore.QRect(60, 220, 71, 41))
        self.btn_maHoa.setObjectName("btn_maHoa")
        self.file_MH = QtWidgets.QPushButton(parent=self.centralwidget)
        self.file_MH.setGeometry(QtCore.QRect(160, 210, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.file_MH.setFont(font)
        self.file_MH.setObjectName("file_MH")
        self.btn_Chuyen = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Chuyen.setGeometry(QtCore.QRect(150, 380, 75, 23))
        self.btn_Chuyen.setObjectName("btn_Chuyen")
        self.luu_MH = QtWidgets.QPushButton(parent=self.centralwidget)
        self.luu_MH.setGeometry(QtCore.QRect(150, 420, 75, 23))
        self.luu_MH.setObjectName("luu_MH")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 50, 100, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(410, 280, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 80, 43, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.btn_giaiMa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_giaiMa.setGeometry(QtCore.QRect(460, 220, 81, 41))
        self.btn_giaiMa.setObjectName("btn_giaiMa")
        self.file_GM = QtWidgets.QPushButton(parent=self.centralwidget)
        self.file_GM.setGeometry(QtCore.QRect(560, 210, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.file_GM.setFont(font)
        self.file_GM.setObjectName("file_GM")
        self.luu_GM = QtWidgets.QPushButton(parent=self.centralwidget)
        self.luu_GM.setGeometry(QtCore.QRect(560, 420, 75, 23))
        self.luu_GM.setObjectName("luu_GM")
        self.show_BM = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.show_BM.setGeometry(QtCore.QRect(60, 280, 321, 91))
        self.show_BM.setObjectName("show_BM")
        self.show_BR = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.show_BR.setGeometry(QtCore.QRect(460, 280, 321, 91))
        self.show_BR.setObjectName("show_BR")
        self.nhap_BM = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.nhap_BM.setGeometry(QtCore.QRect(460, 70, 321, 131))
        self.nhap_BM.setObjectName("nhap_BM")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn_maHoa.clicked.connect(self.runEn)
        self.btn_Chuyen.clicked.connect(self.chuyen)
        self.btn_giaiMa.clicked.connect(self.runDe)
        self.file_MH.clicked.connect(self.filemh)
        self.file_GM.clicked.connect(self.filegm)
        self.luu_MH.clicked.connect(self.luumh)
        self.luu_GM.clicked.connect(self.luugm)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ứng dụng RSA trong truyền tin"))
        self.label_2.setText(_translate("MainWindow", "Người gửi: "))
        self.label_3.setText(_translate("MainWindow", "Bản Rõ"))
        self.label_4.setText(_translate("MainWindow", "Bản Mã"))
        self.btn_maHoa.setText(_translate("MainWindow", "Mã Hoá"))
        self.file_MH.setText(_translate("MainWindow", "File"))
        self.btn_Chuyen.setText(_translate("MainWindow", "Gửi"))
        self.luu_MH.setText(_translate("MainWindow", "Lưu"))
        self.label_5.setText(_translate("MainWindow", "Người nhận: "))
        self.label_6.setText(_translate("MainWindow", "Bản Rõ"))
        self.label_7.setText(_translate("MainWindow", "Bản Mã"))
        self.btn_giaiMa.setText(_translate("MainWindow", "Giải Mã"))
        self.file_GM.setText(_translate("MainWindow", "File"))
        self.luu_GM.setText(_translate("MainWindow", "Lưu"))
           
    def runEn(self):
    # Generate keys
        generateKeys()
        
        # Get the public key and private key
        public_key = pubKey
        private_key=priKey

        # Save the public key and private key to a text file
        self.savePublicKeyToFile(public_key)
        self.savePrivateKeyToFile(private_key)

        # Encrypt the message
        msg = self.nhap_BR.text()
        enc = encrypt(msg, public_key)
        self.show_BM.setText(str(enc))

    def savePublicKeyToFile(self, public_key):
        # Automatically save the public key to the file named "public_key.txt" in the current working directory
        file_name = "public_key.txt"

        # Save the public key to the file
        with open(file_name, 'w', encoding='utf-8') as w:
            w.write("Public Key:\n")
            w.write("N: {}\n".format(public_key[0]))
            w.write("E: {}\n".format(public_key[1]))
            self.label_public_key.setText("Public Key: N={}, E={}".format(public_key[0], public_key[1]))
    def savePrivateKeyToFile(self, private_key):
        # Automatically save the public key to the file named "public_key.txt" in the current working directory
        file_name = "private_key.txt"

        # Save the public key to the file
        with open(file_name, 'w', encoding='utf-8') as w:
            w.write("Private Key:\n")
            w.write("N: {}\n".format(private_key[0]))
            w.write("E: {}\n".format(private_key[1]))
            self.label_public_key.setText("Private Key: N={}, E={}".format(private_key[0], private_key[1]))


    def chuyen(self):
        enctemp=self.show_BM.toPlainText()
        self.nhap_BM.setText(str(enctemp))
    def runDe(self):
        enc=self.nhap_BM.toPlainText()
        dec=decrypt(enc,priKey)
        self.show_BR.setText(str(dec))
    def filemh(self):
        file_name,_=QFileDialog.getOpenFileName(None)
        if file_name:
            with open(file_name, 'r',encoding='utf-8') as f:
                content = f.read()
        self.nhap_BR.setText(str(content))
    def filegm(self):
        file_name, _ = QFileDialog.getOpenFileName(None)
        content = ""  # Initialize content variable
        if file_name:
            with open(file_name, 'r', encoding='utf-8') as f:
                content = f.read()
        self.nhap_BM.setText(str(content))

    def luumh(self):
        content=self.show_BM.toPlainText()
        file_name,_=QFileDialog.getSaveFileName(None)
        if file_name:
            with open(file_name, 'w',encoding='utf-8') as w:
                w.write(content)
    def luugm(self):
        content=self.show_BR.toPlainText()
        file_name,_=QFileDialog.getSaveFileName(None)
        if file_name:
            with open(file_name, 'w',encoding='utf-8') as w:
                w.write(content)  
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

del pubKey,priKey
